import { EntityType, EntityTypes } from "@minecraft/server";

/**
 * All possible MinecraftEntityTypes
 */
export class MinecraftEntityTypes implements EntityTypes {
    private constructor() {
        throw new TypeError("Illegal constructor");
    };
    static get(typeName: string): EntityType | undefined {
        return EntityTypes.get(typeName);
    };
    static getAll(): EntityType[] {
        return Array.from(EntityTypes.getAll());
    };
    static readonly Agent = EntityTypes.get("agent");
    static readonly Allay = EntityTypes.get("allay");
    static readonly AreaEffectCloud = EntityTypes.get("area_effect_cloud");
    static readonly ArmorStand = EntityTypes.get("armor_stand");
    static readonly Arrow = EntityTypes.get("arrow");
    static readonly Axolotl = EntityTypes.get("axolotl");
    static readonly Bat = EntityTypes.get("bat");
    static readonly Bee = EntityTypes.get("bee");
    static readonly Blaze = EntityTypes.get("blaze");
    static readonly Boat = EntityTypes.get("boat");
    static readonly Camel = EntityTypes.get("camel");
    static readonly Cat = EntityTypes.get("cat");
    static readonly CaveSpider = EntityTypes.get("cave_spider");
    static readonly ChestBoat = EntityTypes.get("chest_boat");
    static readonly ChestMinecart = EntityTypes.get("chest_minecart");
    static readonly Chicken = EntityTypes.get("chicken");
    static readonly Cod = EntityTypes.get("cod");
    static readonly CommandBlockMinecart = EntityTypes.get("command_block_minecart");
    static readonly Cow = EntityTypes.get("cow");
    static readonly Creeper = EntityTypes.get("creeper");
    static readonly Dolphin = EntityTypes.get("dolphin");
    static readonly Donkey = EntityTypes.get("donkey");
    static readonly DragonFireball = EntityTypes.get("dragon_fireball");
    static readonly Drowned = EntityTypes.get("drowned");
    static readonly Egg = EntityTypes.get("egg");
    static readonly ElderGuardian = EntityTypes.get("elder_guardian");
    static readonly EnderCrystal = EntityTypes.get("ender_crystal");
    static readonly EnderDragon = EntityTypes.get("ender_dragon");
    static readonly EnderPearl = EntityTypes.get("ender_pearl");
    static readonly Enderman = EntityTypes.get("enderman");
    static readonly Endermite = EntityTypes.get("endermite");
    static readonly EvocationIllager = EntityTypes.get("evocation_illager");
    static readonly EyeOfEnderSignal = EntityTypes.get("eye_of_ender_signal");
    static readonly Fireball = EntityTypes.get("fireball");
    static readonly FireworksRocket = EntityTypes.get("fireworks_rocket");
    static readonly FishingHook = EntityTypes.get("fishing_hook");
    static readonly Fox = EntityTypes.get("fox");
    static readonly Frog = EntityTypes.get("frog");
    static readonly Ghast = EntityTypes.get("ghast");
    static readonly GlowSquid = EntityTypes.get("glow_squid");
    static readonly Goat = EntityTypes.get("goat");
    static readonly Guardian = EntityTypes.get("guardian");
    static readonly Hoglin = EntityTypes.get("hoglin");
    static readonly HopperMinecart = EntityTypes.get("hopper_minecart");
    static readonly Horse = EntityTypes.get("horse");
    static readonly Husk = EntityTypes.get("husk");
    static readonly IronGolem = EntityTypes.get("iron_golem");
    static readonly LightningBolt = EntityTypes.get("lightning_bolt");
    static readonly LingeringPotion = EntityTypes.get("lingering_potion");
    static readonly Llama = EntityTypes.get("llama");
    static readonly LlamaSpit = EntityTypes.get("llama_spit");
    static readonly MagmaCube = EntityTypes.get("magma_cube");
    static readonly Minecart = EntityTypes.get("minecart");
    static readonly Mooshroom = EntityTypes.get("mooshroom");
    static readonly Mule = EntityTypes.get("mule");
    static readonly Npc = EntityTypes.get("npc");
    static readonly Ocelot = EntityTypes.get("ocelot");
    static readonly Panda = EntityTypes.get("panda");
    static readonly Parrot = EntityTypes.get("parrot");
    static readonly Phantom = EntityTypes.get("phantom");
    static readonly Pig = EntityTypes.get("pig");
    static readonly Piglin = EntityTypes.get("piglin");
    static readonly PiglinBrute = EntityTypes.get("piglin_brute");
    static readonly Pillager = EntityTypes.get("pillager");
    static readonly Player = EntityTypes.get("player");
    static readonly PolarBear = EntityTypes.get("polar_bear");
    static readonly Pufferfish = EntityTypes.get("pufferfish");
    static readonly Rabbit = EntityTypes.get("rabbit");
    static readonly Ravager = EntityTypes.get("ravager");
    static readonly Salmon = EntityTypes.get("salmon");
    static readonly Sheep = EntityTypes.get("sheep");
    static readonly Shulker = EntityTypes.get("shulker");
    static readonly ShulkerBullet = EntityTypes.get("shulker_bullet");
    static readonly Silverfish = EntityTypes.get("silverfish");
    static readonly Skeleton = EntityTypes.get("skeleton");
    static readonly SkeletonHorse = EntityTypes.get("skeleton_horse");
    static readonly Slime = EntityTypes.get("slime");
    static readonly SmallFireball = EntityTypes.get("small_fireball");
    static readonly Sniffer = EntityTypes.get("sniffer");
    static readonly SnowGolem = EntityTypes.get("snow_golem");
    static readonly Snowball = EntityTypes.get("snowball");
    static readonly Spider = EntityTypes.get("spider");
    static readonly SplashPotion = EntityTypes.get("splash_potion");
    static readonly Squid = EntityTypes.get("squid");
    static readonly Stray = EntityTypes.get("stray");
    static readonly Strider = EntityTypes.get("strider");
    static readonly Tadpole = EntityTypes.get("tadpole");
    static readonly ThrownTrident = EntityTypes.get("thrown_trident");
    static readonly Tnt = EntityTypes.get("tnt");
    static readonly TntMinecart = EntityTypes.get("tnt_minecart");
    static readonly TraderLlama = EntityTypes.get("trader_llama");
    static readonly TripodCamera = EntityTypes.get("tripod_camera");
    static readonly Tropicalfish = EntityTypes.get("tropicalfish");
    static readonly Turtle = EntityTypes.get("turtle");
    static readonly Vex = EntityTypes.get("vex");
    static readonly Villager = EntityTypes.get("villager");
    static readonly VillagerV2 = EntityTypes.get("villager_v2");
    static readonly Vindicator = EntityTypes.get("vindicator");
    static readonly WanderingTrader = EntityTypes.get("wandering_trader");
    static readonly Warden = EntityTypes.get("warden");
    static readonly Witch = EntityTypes.get("witch");
    static readonly Wither = EntityTypes.get("wither");
    static readonly WitherSkeleton = EntityTypes.get("wither_skeleton");
    static readonly WitherSkull = EntityTypes.get("wither_skull");
    static readonly WitherSkullDangerous = EntityTypes.get("wither_skull_dangerous");
    static readonly Wolf = EntityTypes.get("wolf");
    static readonly XpBottle = EntityTypes.get("xp_bottle");
    static readonly XpOrb = EntityTypes.get("xp_orb");
    static readonly Zoglin = EntityTypes.get("zoglin");
    static readonly Zombie = EntityTypes.get("zombie");
    static readonly ZombieHorse = EntityTypes.get("zombie_horse");
    static readonly ZombiePigman = EntityTypes.get("zombie_pigman");
    static readonly ZombieVillager = EntityTypes.get("zombie_villager");
    static readonly ZombieVillagerV2 = EntityTypes.get("zombie_villager_v2");
}
