import { EntityTypes } from "@minecraft/server";
/**
 * All possible MinecraftEntityTypes
 */
export class MinecraftEntityTypes {
    constructor() {
        throw new TypeError("Illegal constructor");
    }
    ;
    static get(typeName) {
        return EntityTypes.get(typeName);
    }
    ;
    static getAll() {
        return Array.from(EntityTypes.getAll());
    }
    ;
}
MinecraftEntityTypes.Agent = EntityTypes.get("agent");
MinecraftEntityTypes.Allay = EntityTypes.get("allay");
MinecraftEntityTypes.AreaEffectCloud = EntityTypes.get("area_effect_cloud");
MinecraftEntityTypes.ArmorStand = EntityTypes.get("armor_stand");
MinecraftEntityTypes.Arrow = EntityTypes.get("arrow");
MinecraftEntityTypes.Axolotl = EntityTypes.get("axolotl");
MinecraftEntityTypes.Bat = EntityTypes.get("bat");
MinecraftEntityTypes.Bee = EntityTypes.get("bee");
MinecraftEntityTypes.Blaze = EntityTypes.get("blaze");
MinecraftEntityTypes.Boat = EntityTypes.get("boat");
MinecraftEntityTypes.Camel = EntityTypes.get("camel");
MinecraftEntityTypes.Cat = EntityTypes.get("cat");
MinecraftEntityTypes.CaveSpider = EntityTypes.get("cave_spider");
MinecraftEntityTypes.ChestBoat = EntityTypes.get("chest_boat");
MinecraftEntityTypes.ChestMinecart = EntityTypes.get("chest_minecart");
MinecraftEntityTypes.Chicken = EntityTypes.get("chicken");
MinecraftEntityTypes.Cod = EntityTypes.get("cod");
MinecraftEntityTypes.CommandBlockMinecart = EntityTypes.get("command_block_minecart");
MinecraftEntityTypes.Cow = EntityTypes.get("cow");
MinecraftEntityTypes.Creeper = EntityTypes.get("creeper");
MinecraftEntityTypes.Dolphin = EntityTypes.get("dolphin");
MinecraftEntityTypes.Donkey = EntityTypes.get("donkey");
MinecraftEntityTypes.DragonFireball = EntityTypes.get("dragon_fireball");
MinecraftEntityTypes.Drowned = EntityTypes.get("drowned");
MinecraftEntityTypes.Egg = EntityTypes.get("egg");
MinecraftEntityTypes.ElderGuardian = EntityTypes.get("elder_guardian");
MinecraftEntityTypes.EnderCrystal = EntityTypes.get("ender_crystal");
MinecraftEntityTypes.EnderDragon = EntityTypes.get("ender_dragon");
MinecraftEntityTypes.EnderPearl = EntityTypes.get("ender_pearl");
MinecraftEntityTypes.Enderman = EntityTypes.get("enderman");
MinecraftEntityTypes.Endermite = EntityTypes.get("endermite");
MinecraftEntityTypes.EvocationIllager = EntityTypes.get("evocation_illager");
MinecraftEntityTypes.EyeOfEnderSignal = EntityTypes.get("eye_of_ender_signal");
MinecraftEntityTypes.Fireball = EntityTypes.get("fireball");
MinecraftEntityTypes.FireworksRocket = EntityTypes.get("fireworks_rocket");
MinecraftEntityTypes.FishingHook = EntityTypes.get("fishing_hook");
MinecraftEntityTypes.Fox = EntityTypes.get("fox");
MinecraftEntityTypes.Frog = EntityTypes.get("frog");
MinecraftEntityTypes.Ghast = EntityTypes.get("ghast");
MinecraftEntityTypes.GlowSquid = EntityTypes.get("glow_squid");
MinecraftEntityTypes.Goat = EntityTypes.get("goat");
MinecraftEntityTypes.Guardian = EntityTypes.get("guardian");
MinecraftEntityTypes.Hoglin = EntityTypes.get("hoglin");
MinecraftEntityTypes.HopperMinecart = EntityTypes.get("hopper_minecart");
MinecraftEntityTypes.Horse = EntityTypes.get("horse");
MinecraftEntityTypes.Husk = EntityTypes.get("husk");
MinecraftEntityTypes.IronGolem = EntityTypes.get("iron_golem");
MinecraftEntityTypes.LightningBolt = EntityTypes.get("lightning_bolt");
MinecraftEntityTypes.LingeringPotion = EntityTypes.get("lingering_potion");
MinecraftEntityTypes.Llama = EntityTypes.get("llama");
MinecraftEntityTypes.LlamaSpit = EntityTypes.get("llama_spit");
MinecraftEntityTypes.MagmaCube = EntityTypes.get("magma_cube");
MinecraftEntityTypes.Minecart = EntityTypes.get("minecart");
MinecraftEntityTypes.Mooshroom = EntityTypes.get("mooshroom");
MinecraftEntityTypes.Mule = EntityTypes.get("mule");
MinecraftEntityTypes.Npc = EntityTypes.get("npc");
MinecraftEntityTypes.Ocelot = EntityTypes.get("ocelot");
MinecraftEntityTypes.Panda = EntityTypes.get("panda");
MinecraftEntityTypes.Parrot = EntityTypes.get("parrot");
MinecraftEntityTypes.Phantom = EntityTypes.get("phantom");
MinecraftEntityTypes.Pig = EntityTypes.get("pig");
MinecraftEntityTypes.Piglin = EntityTypes.get("piglin");
MinecraftEntityTypes.PiglinBrute = EntityTypes.get("piglin_brute");
MinecraftEntityTypes.Pillager = EntityTypes.get("pillager");
MinecraftEntityTypes.Player = EntityTypes.get("player");
MinecraftEntityTypes.PolarBear = EntityTypes.get("polar_bear");
MinecraftEntityTypes.Pufferfish = EntityTypes.get("pufferfish");
MinecraftEntityTypes.Rabbit = EntityTypes.get("rabbit");
MinecraftEntityTypes.Ravager = EntityTypes.get("ravager");
MinecraftEntityTypes.Salmon = EntityTypes.get("salmon");
MinecraftEntityTypes.Sheep = EntityTypes.get("sheep");
MinecraftEntityTypes.Shulker = EntityTypes.get("shulker");
MinecraftEntityTypes.ShulkerBullet = EntityTypes.get("shulker_bullet");
MinecraftEntityTypes.Silverfish = EntityTypes.get("silverfish");
MinecraftEntityTypes.Skeleton = EntityTypes.get("skeleton");
MinecraftEntityTypes.SkeletonHorse = EntityTypes.get("skeleton_horse");
MinecraftEntityTypes.Slime = EntityTypes.get("slime");
MinecraftEntityTypes.SmallFireball = EntityTypes.get("small_fireball");
MinecraftEntityTypes.Sniffer = EntityTypes.get("sniffer");
MinecraftEntityTypes.SnowGolem = EntityTypes.get("snow_golem");
MinecraftEntityTypes.Snowball = EntityTypes.get("snowball");
MinecraftEntityTypes.Spider = EntityTypes.get("spider");
MinecraftEntityTypes.SplashPotion = EntityTypes.get("splash_potion");
MinecraftEntityTypes.Squid = EntityTypes.get("squid");
MinecraftEntityTypes.Stray = EntityTypes.get("stray");
MinecraftEntityTypes.Strider = EntityTypes.get("strider");
MinecraftEntityTypes.Tadpole = EntityTypes.get("tadpole");
MinecraftEntityTypes.ThrownTrident = EntityTypes.get("thrown_trident");
MinecraftEntityTypes.Tnt = EntityTypes.get("tnt");
MinecraftEntityTypes.TntMinecart = EntityTypes.get("tnt_minecart");
MinecraftEntityTypes.TraderLlama = EntityTypes.get("trader_llama");
MinecraftEntityTypes.TripodCamera = EntityTypes.get("tripod_camera");
MinecraftEntityTypes.Tropicalfish = EntityTypes.get("tropicalfish");
MinecraftEntityTypes.Turtle = EntityTypes.get("turtle");
MinecraftEntityTypes.Vex = EntityTypes.get("vex");
MinecraftEntityTypes.Villager = EntityTypes.get("villager");
MinecraftEntityTypes.VillagerV2 = EntityTypes.get("villager_v2");
MinecraftEntityTypes.Vindicator = EntityTypes.get("vindicator");
MinecraftEntityTypes.WanderingTrader = EntityTypes.get("wandering_trader");
MinecraftEntityTypes.Warden = EntityTypes.get("warden");
MinecraftEntityTypes.Witch = EntityTypes.get("witch");
MinecraftEntityTypes.Wither = EntityTypes.get("wither");
MinecraftEntityTypes.WitherSkeleton = EntityTypes.get("wither_skeleton");
MinecraftEntityTypes.WitherSkull = EntityTypes.get("wither_skull");
MinecraftEntityTypes.WitherSkullDangerous = EntityTypes.get("wither_skull_dangerous");
MinecraftEntityTypes.Wolf = EntityTypes.get("wolf");
MinecraftEntityTypes.XpBottle = EntityTypes.get("xp_bottle");
MinecraftEntityTypes.XpOrb = EntityTypes.get("xp_orb");
MinecraftEntityTypes.Zoglin = EntityTypes.get("zoglin");
MinecraftEntityTypes.Zombie = EntityTypes.get("zombie");
MinecraftEntityTypes.ZombieHorse = EntityTypes.get("zombie_horse");
MinecraftEntityTypes.ZombiePigman = EntityTypes.get("zombie_pigman");
MinecraftEntityTypes.ZombieVillager = EntityTypes.get("zombie_villager");
MinecraftEntityTypes.ZombieVillagerV2 = EntityTypes.get("zombie_villager_v2");
