/**
 * All possible MinecraftEnchantmentTypes
 */
export enum MinecraftEnchantmentTypes {
  Power = "%enchantment.arrowDamage",
  Flame = "%enchantment.arrowFire",
  Infinity = "%enchantment.arrowInfinite",
  Punch = "%enchantment.arrowKnockback",
  Multishot = "%enchantment.crossbowMultishot",
  Piercing = "%enchantment.crossbowPiercing",
  QuickCharge = "%enchantment.crossbowQuickCharge",
  CurseofBinding = "%enchantment.curse.binding",
  CurseofVanishing = "%enchantment.curse.vanishing",
  Sharpness = "%enchantment.damage.all",
  BaneofArthropods = "%enchantment.damage.arthropods",
  Smite = "%enchantment.damage.undead",
  Efficiency = "%enchantment.digging",
  Unbreaking = "%enchantment.durability",
  FireAspect = "%enchantment.fire",
  Lure = "%enchantment.fishingSpeed",
  FrostWalker = "%enchantment.frostwalker",
  Knockback = "%enchantment.knockback",
  Looting = "%enchantment.lootBonus",
  Fortune = "%enchantment.lootBonusDigger",
  LuckoftheSea = "%enchantment.lootBonusFishing",
  Mending = "%enchantment.mending",
  Respiration = "%enchantment.oxygen",
  Protection = "%enchantment.protect.all",
  BlastProtection = "%enchantment.protect.explosion",
  FeatherFalling = "%enchantment.protect.fall",
  FireProtection = "%enchantment.protect.fire",
  ProjectileProtection = "%enchantment.protect.projectile",
  SoulSpeed = "%enchantment.soul_speed",
  SwiftSneak = "%enchantment.swift_sneak",
  Thorns = "%enchantment.thorns",
  SilkTouch = "%enchantment.untouching",
  DepthStrider = "%enchantment.waterWalker",
  AquaAffinity = "%enchantment.waterWorker",
  Channeling = "%enchantment.tridentChanneling",
  Loyalty = "%enchantment.tridentLoyalty",
  Riptide = "%enchantment.tridentRiptide",
  Impaling = "%enchantment.tridentImpaling",
}
