interface BlockPropertiesRoute {
  brushed_progress: 0 | 1 | 2 | 3;
  books_stored: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63;
  propagule_stage: 0 | 1 | 2 | 3 | 4;
  can_summon: false | true;
  bloom: false | true;
  active: false | true;
  item_frame_photo_bit: false | true;
  candles: 0 | 1 | 2 | 3;
  lit: false | true;
  multi_face_direction_bits: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63;
  big_dripleaf_head: false | true;
  big_dripleaf_tilt: "none" | "unstable" | "partial_tilt" | "full_tilt";
  growing_plant_age: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25;
  dripstone_thickness: "tip" | "frustum" | "middle" | "base" | "merge";
  respawn_anchor_charge: 0 | 1 | 2 | 3 | 4;
  twisting_vines_age: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25;
  rotation: 0 | 1 | 2 | 3;
  wall_connection_type_west: "none" | "short" | "tall";
  wall_connection_type_south: "none" | "short" | "tall";
  wall_connection_type_east: "none" | "short" | "tall";
  wall_connection_type_north: "none" | "short" | "tall";
  wall_post_bit: false | true;
  weeping_vines_age: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25;
  honey_level: 0 | 1 | 2 | 3 | 4 | 5;
  block_light_level: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  pillar_axis: "y" | "x" | "z";
  lever_direction: "down_east_west" | "east" | "west" | "south" | "north" | "up_north_south" | "up_east_west" | "down_north_south";
  coral_fan_direction: 0 | 1;
  composter_fill_level: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  extinguished: false | true;
  structure_block_type: "data" | "save" | "load" | "corner" | "invalid" | "export";
  structure_void_type: "void" | "air";
  attachment: "standing" | "hanging" | "side" | "multiple";
  coral_hang_type_bit: false | true;
  stripped_bit: false | true;
  hanging: false | true;
  cauldron_liquid: "water" | "lava" | "powder_snow";
  coral_color: "blue" | "pink" | "purple" | "red" | "yellow";
  sea_grass_type: "default" | "double_top" | "double_bot";
  chemistry_table_type: "compound_creator" | "material_reducer" | "element_constructor" | "lab_table";
  double_plant_type: "sunflower" | "syringa" | "grass" | "fern" | "rose" | "paeonia";
  prismarine_block_type: "default" | "dark" | "bricks";
  wall_block_type: "cobblestone" | "mossy_cobblestone" | "granite" | "diorite" | "andesite" | "sandstone" | "brick" | "stone_brick" | "mossy_stone_brick" | "nether_brick" | "end_brick" | "prismarine" | "red_sandstone" | "red_nether_brick";
  huge_mushroom_bits: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  stone_brick_type: "default" | "mossy" | "cracked" | "chiseled" | "smooth";
  monster_egg_stone_type: "stone" | "cobblestone" | "stone_brick" | "mossy_stone_brick" | "cracked_stone_brick" | "chiseled_stone_brick";
  stone_slab_type_4: "mossy_stone_brick" | "smooth_quartz" | "stone" | "cut_sandstone" | "cut_red_sandstone";
  stone_slab_type_3: "end_stone_brick" | "smooth_red_sandstone" | "polished_andesite" | "andesite" | "diorite" | "polished_diorite" | "granite" | "polished_granite";
  stone_slab_type_2: "red_sandstone" | "purpur" | "prismarine_rough" | "prismarine_dark" | "prismarine_brick" | "mossy_cobblestone" | "smooth_sandstone" | "red_nether_brick";
  stone_slab_type: "smooth_stone" | "sandstone" | "wood" | "cobblestone" | "brick" | "stone_brick" | "quartz" | "nether_brick";
  flower_type: "poppy" | "orchid" | "allium" | "houstonia" | "tulip_red" | "tulip_orange" | "tulip_white" | "tulip_pink" | "oxeye" | "cornflower" | "lily_of_the_valley";
  tall_grass_type: "default" | "tall" | "fern" | "snow";
  sand_stone_type: "default" | "heiroglyphs" | "cut" | "smooth";
  sponge_type: "dry" | "wet";
  new_leaf_type: "acacia" | "dark_oak";
  old_leaf_type: "oak" | "spruce" | "birch" | "jungle";
  deprecated: 0 | 1 | 2 | 3;
  chisel_type: "default" | "chiseled" | "lines" | "smooth";
  new_log_type: "acacia" | "dark_oak";
  old_log_type: "oak" | "spruce" | "birch" | "jungle";
  sand_type: "normal" | "red";
  dirt_type: "normal" | "coarse";
  stone_type: "stone" | "granite" | "granite_smooth" | "diorite" | "diorite_smooth" | "andesite" | "andesite_smooth";
  wood_type: "oak" | "spruce" | "birch" | "jungle" | "acacia" | "dark_oak";
  stability_check: false | true;
  stability: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
  bamboo_leaf_size: "no_leaves" | "small_leaves" | "large_leaves";
  bamboo_stalk_thickness: "thin" | "thick";
  color: "white" | "orange" | "magenta" | "light_blue" | "yellow" | "lime" | "pink" | "gray" | "silver" | "cyan" | "purple" | "blue" | "brown" | "green" | "red" | "black";
  coral_direction: 0 | 1 | 2 | 3;
  weirdo_direction: 0 | 1 | 2 | 3;
  ground_sign_direction: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  cracked_state: "no_cracks" | "cracked" | "max_cracked";
  turtle_egg_count: "one_egg" | "two_egg" | "three_egg" | "four_egg";
  drag_down: false | true;
  torch_facing_direction: "unknown" | "west" | "east" | "north" | "south" | "top";
  sapling_type: "oak" | "spruce" | "birch" | "jungle" | "acacia" | "dark_oak";
  item_frame_map_bit: false | true;
  cluster_count: 0 | 1 | 2 | 3;
  dead_bit: false | true;
  color_bit: false | true;
  allow_underwater_bit: false | true;
  vine_direction_bits: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  upside_down_bit: false | true;
  update_bit: false | true;
  triggered_bit: false | true;
  top_slot_bit: false | true;
  toggle_bit: false | true;
  suspended_bit: false | true;
  repeater_delay: 0 | 1 | 2 | 3;
  redstone_signal: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  rail_direction: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  rail_data_bit: false | true;
  powered_bit: false | true;
  persistent_bit: false | true;
  output_lit_bit: false | true;
  output_subtract_bit: false | true;
  open_bit: false | true;
  occupied_bit: false | true;
  kelp_age: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25;
  no_drop_bit: false | true;
  moisturized_amount: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
  liquid_depth: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  in_wall_bit: false | true;
  infiniburn_bit: false | true;
  height: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
  head_piece_bit: false | true;
  growth: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
  fill_level: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  facing_direction: 0 | 1 | 2 | 3 | 4 | 5;
  explode_bit: false | true;
  end_portal_eye_bit: false | true;
  direction: 0 | 1 | 2 | 3;
  upper_block_bit: false | true;
  door_hinge_bit: false | true;
  disarmed_bit: false | true;
  damage: "undamaged" | "slightly_damaged" | "very_damaged" | "broken";
  covered_bit: false | true;
  conditional_bit: false | true;
  button_pressed_bit: false | true;
  brewing_stand_slot_c_bit: false | true;
  brewing_stand_slot_b_bit: false | true;
  brewing_stand_slot_a_bit: false | true;
  bite_counter: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  portal_axis: "unknown" | "x" | "z";
  attached_bit: false | true;
  age: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  age_bit: false | true;
}

export type BlockProperties = Partial<BlockPropertiesRoute>;